version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=militex
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      bash -c "python backend/manage.py migrate &&
              python backend/manage.py collectstatic --noinput &&
              gunicorn militex.wsgi:application --bind 0.0.0.0:8000 --chdir backend"
    volumes:
      - .:/app
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/militex
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume: