# Generated by Django 4.2.11 on 2025-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_imported",
            field=models.BooleanField(default=False, verbose_name="Is Imported"),
        ),
        migrations.AddField(
            model_name="car",
            name="original_url",
            field=models.URLField(blank=True, null=True, verbose_name="Original URL"),
        ),
    ]
