# Generated by Django 4.2.11 on 2025-04-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
