# Generated by Django 4.2.11 on 2025-05-01 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_remove_carimage_car_delete_car_delete_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year of Manufacture')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Vehicle Type')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=20, verbose_name='Condition')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, verbose_name='Fuel Type')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], max_length=20, verbose_name='Transmission')),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('estate', 'Estate'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('liftback', 'Liftback'), ('coupe', 'Coupe'), ('fastback', 'Fastback'), ('hardtop', 'Hardtop')], max_length=20, null=True, verbose_name='Body Type')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City/Region')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('negotiable', models.BooleanField(default=False, verbose_name='Negotiable Price')),
                ('engine_size', models.FloatField(blank=True, null=True, verbose_name='Engine Size')),
                ('engine_power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine Power (HP)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(blank=True, null=True, verbose_name='Original URL')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Is Imported')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
